plugins { id 'java-library' }
tasks.withType(JavaCompile).configureEach { options.release = 17 }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8' }
dependencies {
    api "com.badlogicgames.gdx:gdx:$gdxVersion"
    testImplementation 'junit:junit:4.13.2'
}
test { testLogging { events 'passed', 'failed', 'skipped'; exceptionFormat 'full'; showStandardStreams = true }; maxHeapSize = '1g' }
