plugins { id 'application' }
tasks.withType(JavaCompile).configureEach { options.release = 17 }
application { mainClass = 'com.hotatticgames.climbup.desktop.DesktopLauncher' }
dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx-controllers:gdx-controllers-core:$controllersVersion"
    implementation "com.badlogicgames.gdx-controllers:gdx-controllers-desktop:$controllersVersion"
    testImplementation 'junit:junit:4.13.2'
}
tasks.named("test") { testLogging { events "passed", "failed", "skipped"; exceptionFormat "full" } }
tasks.named("run") {
    workingDir = file('../assets')
    systemProperties System.properties.findAll { it.key.toString().startsWith('climb.') }
}
